[package]
name = "gravitate"
version = "8.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
# lto = "fat" # TODO uncomment when ready for release

[dependencies]
chrono = "^0.4"
dirs = "^4"
fltk = { version = "^1.2", features = ["no-pango",], git = "https://github.com/fltk-rs/fltk-rs" }
num = "^0.4"
rust-ini = "^0.17"
state = "^0.5"
thousands = "^0.2.0"
